- hosts: all
  gather_facts: no
  tasks:
  - name: copy file
    copy: src=check_nginx_process.py dest=/opt/check_nginx_process.py owner=root mode=755
  - name: Execute Script
    shell: python /opt/check_nginx_process.py
    register: out
  - name: display ping host result
    debug: var=out verbosity=2
